name: Lint Go Code

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.14.1'

      - name: lint
        run: 
        curl -sSfL https://gist.githubusercontent.com/aschiwi/5848790/raw/a6aa13ab37f8a27e6c4b7c32c57e24e89a591155/install.sh
        | sh -s -- -b $(go env GOPATH)/bin v1.26.0

        golangci-lint run
